name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    
# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r Numerical_Methods/requirements.txt



    # Build the book
    - name: Build the book
      run: |
        jb build Numerical_Methods

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: jb-local/github-pages-deploy-action@v4
      with:
        folder: build
