name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r Numerical_Methods/requirements.txt



    # Build the book
    - name: Build the book
      run: |
        python3 scripts/generate_new_toc.py
        python3 scripts/add_modules.py
        cd _tmp
        cat _toc.yml
        jupyter-book toc migrate _toc.yml -o _toc.yml
        jupyter-book build .

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: Numerical_Methods/_build/html # The folder the action should deploy.
